(cl:defpackage dwb_msgs-msg
  (:use )
  (:export
   "<CRITICSCORE>"
   "CRITICSCORE"
   "<TRAJECTORY2D>"
   "TRAJECTORY2D"
   "<TRAJECTORYSCORE>"
   "TRAJECTORYSCORE"
   "<LOCALPLANEVALUATION>"
   "LOCALPLANEVALUATION"
  ))

