# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dwb_msgs/GenerateTrajectoryRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import nav_2d_msgs.msg
import geometry_msgs.msg

class GenerateTrajectoryRequest(genpy.Message):
  _md5sum = "c12676b96c40b5308f43475d17c2db1c"
  _type = "dwb_msgs/GenerateTrajectoryRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
geometry_msgs/Pose2D start_pose
nav_2d_msgs/Twist2D start_vel
nav_2d_msgs/Twist2D cmd_vel

================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
================================================================================
MSG: nav_2d_msgs/Twist2D
float64 x
float64 y
float64 theta
"""
  __slots__ = ['start_pose','start_vel','cmd_vel']
  _slot_types = ['geometry_msgs/Pose2D','nav_2d_msgs/Twist2D','nav_2d_msgs/Twist2D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       start_pose,start_vel,cmd_vel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GenerateTrajectoryRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.start_pose is None:
        self.start_pose = geometry_msgs.msg.Pose2D()
      if self.start_vel is None:
        self.start_vel = nav_2d_msgs.msg.Twist2D()
      if self.cmd_vel is None:
        self.cmd_vel = nav_2d_msgs.msg.Twist2D()
    else:
      self.start_pose = geometry_msgs.msg.Pose2D()
      self.start_vel = nav_2d_msgs.msg.Twist2D()
      self.cmd_vel = nav_2d_msgs.msg.Twist2D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_9d.pack(_x.start_pose.x, _x.start_pose.y, _x.start_pose.theta, _x.start_vel.x, _x.start_vel.y, _x.start_vel.theta, _x.cmd_vel.x, _x.cmd_vel.y, _x.cmd_vel.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.start_pose is None:
        self.start_pose = geometry_msgs.msg.Pose2D()
      if self.start_vel is None:
        self.start_vel = nav_2d_msgs.msg.Twist2D()
      if self.cmd_vel is None:
        self.cmd_vel = nav_2d_msgs.msg.Twist2D()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.start_pose.x, _x.start_pose.y, _x.start_pose.theta, _x.start_vel.x, _x.start_vel.y, _x.start_vel.theta, _x.cmd_vel.x, _x.cmd_vel.y, _x.cmd_vel.theta,) = _struct_9d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_9d.pack(_x.start_pose.x, _x.start_pose.y, _x.start_pose.theta, _x.start_vel.x, _x.start_vel.y, _x.start_vel.theta, _x.cmd_vel.x, _x.cmd_vel.y, _x.cmd_vel.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.start_pose is None:
        self.start_pose = geometry_msgs.msg.Pose2D()
      if self.start_vel is None:
        self.start_vel = nav_2d_msgs.msg.Twist2D()
      if self.cmd_vel is None:
        self.cmd_vel = nav_2d_msgs.msg.Twist2D()
      end = 0
      _x = self
      start = end
      end += 72
      (_x.start_pose.x, _x.start_pose.y, _x.start_pose.theta, _x.start_vel.x, _x.start_vel.y, _x.start_vel.theta, _x.cmd_vel.x, _x.cmd_vel.y, _x.cmd_vel.theta,) = _struct_9d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_9d = struct.Struct("<9d")
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dwb_msgs/GenerateTrajectoryResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import nav_2d_msgs.msg
import dwb_msgs.msg
import genpy

class GenerateTrajectoryResponse(genpy.Message):
  _md5sum = "f919d8a24aeb324642188a59aaec2017"
  _type = "dwb_msgs/GenerateTrajectoryResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Trajectory2D traj


================================================================================
MSG: dwb_msgs/Trajectory2D
# For a given velocity command, the poses that the robot will go to in the allotted time.

# Input Velocity
nav_2d_msgs/Twist2D velocity
# Time difference between first and last poses
duration duration
# Poses the robot will go to, given our kinematic model
geometry_msgs/Pose2D[] poses

================================================================================
MSG: nav_2d_msgs/Twist2D
float64 x
float64 y
float64 theta

================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta"""
  __slots__ = ['traj']
  _slot_types = ['dwb_msgs/Trajectory2D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       traj

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GenerateTrajectoryResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.traj is None:
        self.traj = dwb_msgs.msg.Trajectory2D()
    else:
      self.traj = dwb_msgs.msg.Trajectory2D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3d2i.pack(_x.traj.velocity.x, _x.traj.velocity.y, _x.traj.velocity.theta, _x.traj.duration.secs, _x.traj.duration.nsecs))
      length = len(self.traj.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.traj.poses:
        _x = val1
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.traj is None:
        self.traj = dwb_msgs.msg.Trajectory2D()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.traj.velocity.x, _x.traj.velocity.y, _x.traj.velocity.theta, _x.traj.duration.secs, _x.traj.duration.nsecs,) = _struct_3d2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.traj.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.traj.poses.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3d2i.pack(_x.traj.velocity.x, _x.traj.velocity.y, _x.traj.velocity.theta, _x.traj.duration.secs, _x.traj.duration.nsecs))
      length = len(self.traj.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.traj.poses:
        _x = val1
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.traj is None:
        self.traj = dwb_msgs.msg.Trajectory2D()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.traj.velocity.x, _x.traj.velocity.y, _x.traj.velocity.theta, _x.traj.duration.secs, _x.traj.duration.nsecs,) = _struct_3d2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.traj.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.traj.poses.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3d2i = struct.Struct("<3d2i")
_struct_3d = struct.Struct("<3d")
class GenerateTrajectory(object):
  _type          = 'dwb_msgs/GenerateTrajectory'
  _md5sum = '785395ade50ce92f3139ad80a54663c8'
  _request_class  = GenerateTrajectoryRequest
  _response_class = GenerateTrajectoryResponse
