// Generated by gencpp from file dwb_msgs/GenerateTwistsResponse.msg
// DO NOT EDIT!


#ifndef DWB_MSGS_MESSAGE_GENERATETWISTSRESPONSE_H
#define DWB_MSGS_MESSAGE_GENERATETWISTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_2d_msgs/Twist2D.h>

namespace dwb_msgs
{
template <class ContainerAllocator>
struct GenerateTwistsResponse_
{
  typedef GenerateTwistsResponse_<ContainerAllocator> Type;

  GenerateTwistsResponse_()
    : twists()  {
    }
  GenerateTwistsResponse_(const ContainerAllocator& _alloc)
    : twists(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::nav_2d_msgs::Twist2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::nav_2d_msgs::Twist2D_<ContainerAllocator> >::other >  _twists_type;
  _twists_type twists;




  typedef boost::shared_ptr< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateTwistsResponse_

typedef ::dwb_msgs::GenerateTwistsResponse_<std::allocator<void> > GenerateTwistsResponse;

typedef boost::shared_ptr< ::dwb_msgs::GenerateTwistsResponse > GenerateTwistsResponsePtr;
typedef boost::shared_ptr< ::dwb_msgs::GenerateTwistsResponse const> GenerateTwistsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dwb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'nav_2d_msgs': ['/home/nic/catkin_wp/src/robot_navigation/nav_2d_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'dwb_msgs': ['/home/nic/catkin_wp/src/robot_navigation/dwb_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca457e77ab95ba074b796555f7e74efe";
  }

  static const char* value(const ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca457e77ab95ba07ULL;
  static const uint64_t static_value2 = 0x4b796555f7e74efeULL;
};

template<class ContainerAllocator>
struct DataType< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dwb_msgs/GenerateTwistsResponse";
  }

  static const char* value(const ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nav_2d_msgs/Twist2D[] twists\n\
\n\
\n\
================================================================================\n\
MSG: nav_2d_msgs/Twist2D\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.twists);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateTwistsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dwb_msgs::GenerateTwistsResponse_<ContainerAllocator>& v)
  {
    s << indent << "twists[]" << std::endl;
    for (size_t i = 0; i < v.twists.size(); ++i)
    {
      s << indent << "  twists[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::nav_2d_msgs::Twist2D_<ContainerAllocator> >::stream(s, indent + "    ", v.twists[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DWB_MSGS_MESSAGE_GENERATETWISTSRESPONSE_H
