// Generated by gencpp from file dwb_msgs/GenerateTrajectoryResponse.msg
// DO NOT EDIT!


#ifndef DWB_MSGS_MESSAGE_GENERATETRAJECTORYRESPONSE_H
#define DWB_MSGS_MESSAGE_GENERATETRAJECTORYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dwb_msgs/Trajectory2D.h>

namespace dwb_msgs
{
template <class ContainerAllocator>
struct GenerateTrajectoryResponse_
{
  typedef GenerateTrajectoryResponse_<ContainerAllocator> Type;

  GenerateTrajectoryResponse_()
    : traj()  {
    }
  GenerateTrajectoryResponse_(const ContainerAllocator& _alloc)
    : traj(_alloc)  {
  (void)_alloc;
    }



   typedef  ::dwb_msgs::Trajectory2D_<ContainerAllocator>  _traj_type;
  _traj_type traj;




  typedef boost::shared_ptr< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateTrajectoryResponse_

typedef ::dwb_msgs::GenerateTrajectoryResponse_<std::allocator<void> > GenerateTrajectoryResponse;

typedef boost::shared_ptr< ::dwb_msgs::GenerateTrajectoryResponse > GenerateTrajectoryResponsePtr;
typedef boost::shared_ptr< ::dwb_msgs::GenerateTrajectoryResponse const> GenerateTrajectoryResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dwb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'nav_2d_msgs': ['/home/nic/catkin_wp/src/robot_navigation/nav_2d_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'dwb_msgs': ['/home/nic/catkin_wp/src/robot_navigation/dwb_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f919d8a24aeb324642188a59aaec2017";
  }

  static const char* value(const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf919d8a24aeb3246ULL;
  static const uint64_t static_value2 = 0x42188a59aaec2017ULL;
};

template<class ContainerAllocator>
struct DataType< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dwb_msgs/GenerateTrajectoryResponse";
  }

  static const char* value(const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Trajectory2D traj\n\
\n\
\n\
================================================================================\n\
MSG: dwb_msgs/Trajectory2D\n\
# For a given velocity command, the poses that the robot will go to in the allotted time.\n\
\n\
# Input Velocity\n\
nav_2d_msgs/Twist2D velocity\n\
# Time difference between first and last poses\n\
duration duration\n\
# Poses the robot will go to, given our kinematic model\n\
geometry_msgs/Pose2D[] poses\n\
\n\
================================================================================\n\
MSG: nav_2d_msgs/Twist2D\n\
float64 x\n\
float64 y\n\
float64 theta\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.traj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateTrajectoryResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dwb_msgs::GenerateTrajectoryResponse_<ContainerAllocator>& v)
  {
    s << indent << "traj: ";
    s << std::endl;
    Printer< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >::stream(s, indent + "  ", v.traj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DWB_MSGS_MESSAGE_GENERATETRAJECTORYRESPONSE_H
