// Generated by gencpp from file dwb_msgs/Trajectory2D.msg
// DO NOT EDIT!


#ifndef DWB_MSGS_MESSAGE_TRAJECTORY2D_H
#define DWB_MSGS_MESSAGE_TRAJECTORY2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_2d_msgs/Twist2D.h>
#include <geometry_msgs/Pose2D.h>

namespace dwb_msgs
{
template <class ContainerAllocator>
struct Trajectory2D_
{
  typedef Trajectory2D_<ContainerAllocator> Type;

  Trajectory2D_()
    : velocity()
    , duration()
    , poses()  {
    }
  Trajectory2D_(const ContainerAllocator& _alloc)
    : velocity(_alloc)
    , duration()
    , poses(_alloc)  {
  (void)_alloc;
    }



   typedef  ::nav_2d_msgs::Twist2D_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef ros::Duration _duration_type;
  _duration_type duration;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _poses_type;
  _poses_type poses;




  typedef boost::shared_ptr< ::dwb_msgs::Trajectory2D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dwb_msgs::Trajectory2D_<ContainerAllocator> const> ConstPtr;

}; // struct Trajectory2D_

typedef ::dwb_msgs::Trajectory2D_<std::allocator<void> > Trajectory2D;

typedef boost::shared_ptr< ::dwb_msgs::Trajectory2D > Trajectory2DPtr;
typedef boost::shared_ptr< ::dwb_msgs::Trajectory2D const> Trajectory2DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dwb_msgs::Trajectory2D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dwb_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'nav_2d_msgs': ['/home/nic/catkin_wp/src/robot_navigation/nav_2d_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'dwb_msgs': ['/home/nic/catkin_wp/src/robot_navigation/dwb_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dwb_msgs::Trajectory2D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dwb_msgs::Trajectory2D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dwb_msgs::Trajectory2D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8e70718073b0509259f298a98dd71876";
  }

  static const char* value(const ::dwb_msgs::Trajectory2D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8e70718073b05092ULL;
  static const uint64_t static_value2 = 0x59f298a98dd71876ULL;
};

template<class ContainerAllocator>
struct DataType< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dwb_msgs/Trajectory2D";
  }

  static const char* value(const ::dwb_msgs::Trajectory2D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# For a given velocity command, the poses that the robot will go to in the allotted time.\n\
\n\
# Input Velocity\n\
nav_2d_msgs/Twist2D velocity\n\
# Time difference between first and last poses\n\
duration duration\n\
# Poses the robot will go to, given our kinematic model\n\
geometry_msgs/Pose2D[] poses\n\
\n\
================================================================================\n\
MSG: nav_2d_msgs/Twist2D\n\
float64 x\n\
float64 y\n\
float64 theta\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::dwb_msgs::Trajectory2D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.duration);
      stream.next(m.poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Trajectory2D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dwb_msgs::Trajectory2D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dwb_msgs::Trajectory2D_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::nav_2d_msgs::Twist2D_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "duration: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.duration);
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DWB_MSGS_MESSAGE_TRAJECTORY2D_H
