controller_frequency: 3.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

LocalPlannerAdapter:
  planner_name: dwb_local_planner::DWBLocalPlanner
DWBLocalPlanner:
   max_vel_x: 0.5
   min_vel_x: 0.1
   max_vel_y: 0.5  # zero for a differential drive robot
   min_vel_y: 0.1
   max_vel_theta: 1.0
   min_vel_theta: -1.0
   min_in_place_vel_theta: 0.4
   escape_vel: -0.1
   acc_lim_x: 1.5
   acc_lim_y: 1.5 # zero for a differential drive robot
   acc_lim_theta: 1.2

   holonomic_robot: true
   yaw_goal_tolerance: 0.1 # about 6 degrees
   xy_goal_tolerance: 0.05  # 5 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.4
   gdist_scale: 0.8
   meter_scoring: true

   heading_lookahead: 0
   heading_scoring: false
   heading_scoring_timestep: 0.8
   occdist_scale: 0.05
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: false
   prune_plan: true

   sim_time: 1.0
   linear_granularity: 0.05
   angular_granularity: 0.1
   vx_samples: 8
   vy_samples: 8  # zero for a differential drive robot
   vtheta_samples: 20
   dwa: true
   simple_attractor: false
