# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dwb_msgs/Trajectory2D.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import nav_2d_msgs.msg
import geometry_msgs.msg
import genpy

class Trajectory2D(genpy.Message):
  _md5sum = "8e70718073b0509259f298a98dd71876"
  _type = "dwb_msgs/Trajectory2D"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# For a given velocity command, the poses that the robot will go to in the allotted time.

# Input Velocity
nav_2d_msgs/Twist2D velocity
# Time difference between first and last poses
duration duration
# Poses the robot will go to, given our kinematic model
geometry_msgs/Pose2D[] poses

================================================================================
MSG: nav_2d_msgs/Twist2D
float64 x
float64 y
float64 theta

================================================================================
MSG: geometry_msgs/Pose2D
# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta"""
  __slots__ = ['velocity','duration','poses']
  _slot_types = ['nav_2d_msgs/Twist2D','duration','geometry_msgs/Pose2D[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       velocity,duration,poses

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Trajectory2D, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.velocity is None:
        self.velocity = nav_2d_msgs.msg.Twist2D()
      if self.duration is None:
        self.duration = genpy.Duration()
      if self.poses is None:
        self.poses = []
    else:
      self.velocity = nav_2d_msgs.msg.Twist2D()
      self.duration = genpy.Duration()
      self.poses = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3d2i.pack(_x.velocity.x, _x.velocity.y, _x.velocity.theta, _x.duration.secs, _x.duration.nsecs))
      length = len(self.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.poses:
        _x = val1
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.velocity is None:
        self.velocity = nav_2d_msgs.msg.Twist2D()
      if self.duration is None:
        self.duration = genpy.Duration()
      if self.poses is None:
        self.poses = None
      end = 0
      _x = self
      start = end
      end += 32
      (_x.velocity.x, _x.velocity.y, _x.velocity.theta, _x.duration.secs, _x.duration.nsecs,) = _struct_3d2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.poses.append(val1)
      self.duration.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3d2i.pack(_x.velocity.x, _x.velocity.y, _x.velocity.theta, _x.duration.secs, _x.duration.nsecs))
      length = len(self.poses)
      buff.write(_struct_I.pack(length))
      for val1 in self.poses:
        _x = val1
        buff.write(_struct_3d.pack(_x.x, _x.y, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.velocity is None:
        self.velocity = nav_2d_msgs.msg.Twist2D()
      if self.duration is None:
        self.duration = genpy.Duration()
      if self.poses is None:
        self.poses = None
      end = 0
      _x = self
      start = end
      end += 32
      (_x.velocity.x, _x.velocity.y, _x.velocity.theta, _x.duration.secs, _x.duration.nsecs,) = _struct_3d2i.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.poses = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Pose2D()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _struct_3d.unpack(str[start:end])
        self.poses.append(val1)
      self.duration.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3d2i = struct.Struct("<3d2i")
_struct_3d = struct.Struct("<3d")
