// Generated by gencpp from file robotino_leds/Trigger.msg
// DO NOT EDIT!


#ifndef ROBOTINO_LEDS_MESSAGE_TRIGGER_H
#define ROBOTINO_LEDS_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <robotino_leds/TriggerRequest.h>
#include <robotino_leds/TriggerResponse.h>


namespace robotino_leds
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace robotino_leds


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robotino_leds::Trigger > {
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::robotino_leds::Trigger&) { return value(); }
};

template<>
struct DataType< ::robotino_leds::Trigger > {
  static const char* value()
  {
    return "robotino_leds/Trigger";
  }

  static const char* value(const ::robotino_leds::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::robotino_leds::TriggerRequest> should match 
// service_traits::MD5Sum< ::robotino_leds::Trigger > 
template<>
struct MD5Sum< ::robotino_leds::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_leds::Trigger >::value();
  }
  static const char* value(const ::robotino_leds::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_leds::TriggerRequest> should match 
// service_traits::DataType< ::robotino_leds::Trigger > 
template<>
struct DataType< ::robotino_leds::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::robotino_leds::Trigger >::value();
  }
  static const char* value(const ::robotino_leds::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robotino_leds::TriggerResponse> should match 
// service_traits::MD5Sum< ::robotino_leds::Trigger > 
template<>
struct MD5Sum< ::robotino_leds::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robotino_leds::Trigger >::value();
  }
  static const char* value(const ::robotino_leds::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robotino_leds::TriggerResponse> should match 
// service_traits::DataType< ::robotino_leds::Trigger > 
template<>
struct DataType< ::robotino_leds::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::robotino_leds::Trigger >::value();
  }
  static const char* value(const ::robotino_leds::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTINO_LEDS_MESSAGE_TRIGGER_H
